### ISSUE TITLE
HK: Classify Callback Reasons (meetings) and display it cross with agents and Conversion Rate

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#259]
Created Excel file on SharePoint to select the Callback Reason (`Meetings` table) and maintain a manual Exceptions table.

Merged reason into `Meetings` table of ITD TV 2.0.

Developing report.

**Comment by CesarITD** [comment]
It is important to leave documented in the delivery of the requirement that the key point of this have the Pick List Callback Reason in the CRM and until this is not implemented the handling of this data  in the BI side takes a lot of time to maintain and even so the results are not safe because where the CRM reason is put is an open text field.

**Comment by jesusitd** [comment]
![image](https://user-images.githubusercontent.com/50643267/64866156-dc8fba00-d608-11e9-9b19-28a41550bb5e.png)
- and Leads Calls cannot be directly linked to Leads Meetings

**Comment by jesusitd** [comment]
`Callbacks Reports` relaunched over email to Operations workspace with requested features.
