### ISSUE TITLE
HK, Ad Spend By Provider: Add to 2000 all the spends from Google Bing etc to the reconciliation

### ISSUE THREAD

**Issue by jesusitd** [intakedesk/PowerBI-General#413]

**Comment by CesarITD** [comment]
Report was with a filter to Source = Facebook because we had comparation FB Results vs CRM Leads. The report was changed and now Ad Spend has ALL Sources. A new column was added with AD Spend just for Facebook. The break for source is not possible because in the data side of QuickBooks we got all spend just for Provider. New Report version was sent to HK.
