### ISSUE TITLE
HK: Ensure that the new implementation of Status does not break the reports.

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#471]

**Comment by CesarITD** [comment]
1. Inspect M queries and Data model for Status alterations/calculations
	2. Plan ahead of changes that must be made
	3. Report ourselves as ready for change

**Comment by CesarITD** [comment]
C:\Users\jesus\Intakedesk LLC\Power BI Documentation - Power BI Desktop Files\Python Scripts\csv
 
SEARCH KEYWORKDS HERE FOR STATUS/DISPO MANIPULATION. THIS IS COMING FROM PY PBIX ANALYZER

**Comment by CesarITD** [comment]
[awko.m.txt](https://github.com/intakedesk/PowerBI-General/files/4222251/awko.m.txt)
[3000.m.txt](https://github.com/intakedesk/PowerBI-General/files/4222252/3000.m.txt)
[tv2.0.m.txt](https://github.com/intakedesk/PowerBI-General/files/4222253/tv2.0.m.txt)

**Comment by jesusitd** [comment]
As per our conversation:
1. Inspect M queries and Data model for Status alterations/calculations
2. Plan ahead of changes that must be made
3. Wait for new fields to be entirely deployed (`tort_decline_reason`, `turn_down_reason`?, `intake_status`, `verification_status`)
4. Verify with SQL that expected behavior with scripts from Nick is achieved (Jesus)
5. Import new fields into TV 2.0
6. Duplicate a set of target columns / measures that should behave the same with new model
7. Deploy a comparison tab in Data Sweep reports
8. (Jesus suggests) DO SOME SORT OF INTERNAL Additional VALIDATION
9. Notify everybody as ready for deploying
10. TRY NOT TO LET TIME PASS WAITING FOR AN APPROVAL. We might be left behind again

Upon approval:
- Delete validation tab in Data Sweep
- Copy new definition to target columns / measures
- Delete duplicated test-purposed columns / measures

@CesarITD

**Comment by jesusitd** [comment]
Nick file:
[Lead Status - Buckets.xlsx](https://github.com/intakedesk/PowerBI-General/files/4225974/Lead.Status.-.Buckets.xlsx)

**Comment by jesusitd** [comment]
Done planning changes until deployment to production is received.

**Log**:
https://intakedesk.sharepoint.com/:w:/r/sites/power-bi-docs/Power%20BI%20Desktop%20Files/-%20Documents/General%20Tasks/2020-19-02%20New%20Lead%20Status%20Fields%20plan.docx?d=w40ac82b405094bafa9f2060cfbe0f273&csf=1&e=TI3QPp

WAITING DEPLOYMENT.

**Comment by jesusitd** [comment]
Steps agreed Cesar / Jesus (after meeting with HK, NM):
1. Import New Fields (Lead Status 2, Intake Status, Ver Status), only for Tort Vision 2.0
2. Calculate a GLOBAL STATUS (similar to current Lead Status) organized by Lead/Intake/Case categories
3. With the New Global Status and the 3 component statuses, generate a new tab in Data Sweep that allows to compare Old Lead Status, New Global Lead Status, New Lead (Only) Status, New Intake Status and New Ver Status

IF APPROVED AND VALIDATED:
1. Current Lead Status **CAN BE REPLACED** with the New Global Status, which will be conveniently labeled as:
- Lead: Some status
- ...
- Intake: Some Status...
- Case: Some status...
2. The three categories of statuses could be sliced by `Lead Status Category`: Lead Status, Intake Status, Case Status

**Comment by jesusitd** [comment]
[Lead Status - Buckets 2020-02-25.xlsx](https://github.com/intakedesk/PowerBI-General/files/4251012/Lead.Status.-.Buckets.2020-02-25.xlsx)
Sent this file with Visual Mappings to NM and AG

**Comment by jesusitd** [comment]
Waiting on comments from Management, NM and HK

**Comment by jesusitd** [comment]
Aged out.
